/// <reference types="Cypress"/>
/// <reference types="cypress-xpath"/>
const CREDENTIALS = require('../fixtures/Credentials.json')
import 'cypress-wait-until';

describe('Workbench login and Dashboard',function()
{
    it.skip('WF3-Assign User role', function()
    {
        cy.Signin(CREDENTIALS.Useradmin,CREDENTIALS.adminpwd)
        cy.contains('testing project').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .nav-link').click({force:true})
        Cypress.on('uncaught:exception', (err, runnable) => {return false;});
        // cy.get('[title="2"] > .page-link').click()
        cy.get('tbody > :nth-child(1) > :nth-child(2) > :nth-child(1) > span')
            .should('include.text','Automation Project')
        cy.get(':nth-child(1) > :nth-child(5) > :nth-child(1) > div > [title="Assign User"] > .fas')
          .click()
        cy.get(':nth-child(1)>.selection-cell>input').check().should('be.checked')
        cy.wait(1000)
        cy.get('select').eq(0).select('14').should('include.text','lalitha g')
        cy.get('.blue').click()
        cy.get('.ajs-message').should('have.text','workflow3 task cannot be assigned to user role. ')
        cy.wait(3000)
    // })
    // it('Reopen WF3 from TSD', function()
    // {
        cy.get(':nth-child(4) > .nav-link').click({force:true})
        Cypress.on('uncaught:exception', (err, runnable) => {return false;});
        cy.get(':nth-child(4)>.nav-link').click().should('have.text',' Projects')
        cy.get(':nth-child(1)>:nth-child(2)>:nth-child(1)>:nth-child(2)>:nth-child(1)>div>[title="Task Summary Data Report"]')
          .click()
        //Status and euid
        cy.get(':nth-child(1) > .css-10xt3zp-container > .css-tu25sd-control').type('Act{enter}')
          .should('have.text','Active Review')
        cy.get(':nth-child(2) > .css-10xt3zp-container > .css-tu25sd-control').type('847a3{enter}')
          .should('have.text','115ad4faa9bbf5b847a3')
        cy.get('.row > :nth-child(1) > input').check().should('be.checked')
        cy.get('.blue').click().should('have.text','Get Data')
        cy.wait(10000)
        cy.get('.panel-body').scrollTo('center')
        cy.wait(20000)
        cy.get('#CommentsId').type('check all data').should('have.text','check all data')
        cy.contains('Submit').click()
        cy.get('.panel-body').scrollTo('top')
        cy.get(':nth-child(2) > input').check().should('be.checked')
        cy.get('.col-md-2 > .css-10xt3zp-container > .css-tu25sd-control').type('lal{enter}')
        .should('have.text','lalitha g')
        cy.contains('Re-Open').click().should('have.text','Re-Open')
        cy.wait(1000)
        cy.get('#commentsArea').type('Done').should('have.text','Done')
        cy.get('form > div > .blue').click().should('have.text','Submit')
    })
    it('ReAssign to User role', function()
    {
        cy.Signin(CREDENTIALS.Useradmin,CREDENTIALS.adminpwd)
        cy.contains('testing project').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .nav-link').click({force:true})
        Cypress.on('uncaught:exception', (err, runnable) => {   return false;   });
        // cy.get('[title="2"] > .page-link').click()
        // cy.get('tbody > :nth-child(1) > :nth-child(2) > :nth-child(1) > span')
        //     .should('include.text','Automation Project')
        cy.get(':nth-child(1) > :nth-child(5) > :nth-child(1) > div > [title="Assign User"] > .fas')
          .click()
        cy.wait(3000)
        cy.get('#react-tabs-24').should('have.text','New').click()
        cy.get('#text-filter-column-status').type('R')
        // cy.get('[aria-label="Status sortable"] > .order > .dropup > .caret').click()
        cy.get(':nth-child(1)>[type="checkbox"]').click({force:true})
        cy.get('select').eq(0).select('17').should('include.text','firstname Lokireddy')
        // cy.get('.blue').click()
        // cy.get('.ajs-message').should('have.text','workflow3 task cannot be assigned to user role. ')
    })
})