/// <reference types="Cypress"/>
/// <reference types="cypress-xpath"/>
const CREDENTIALS = require('../fixtures/Credentials.json')
import 'cypress-wait-until';

describe('Workbench login and Dashboard',function()
{
    it.skip('Admin assign WF2 task',function()
    {
        cy.User1(CREDENTIALS.Useradmin,CREDENTIALS.Pwd)
        cy.intercept('/workbench/dashboard/getProjectDataByUserIDOrProjectID?projectId=210&status=Draft')
        .as('draft')
        cy.contains('testing project').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .nav-link').click({force:true})
        Cypress.on('uncaught:exception', (err, runnable) => {return false;});
        cy.get('[title="5"] > .page-link').click()
        cy.get('tbody > :nth-child(4) > :nth-child(2) > :nth-child(1) > span')
            .should('include.text','TestCypProject')
        cy.get(':nth-child(4) > :nth-child(5) > :nth-child(1) > div > [title="Assign User"] > .fas')
          .click()
        cy.wait('@draft')
        cy.get(':nth-child(1)>.selection-cell>input').check().should('be.checked')
        cy.get('select').eq(1).select('2').should('include.text','workflow2')
        cy.wait(1000)
        cy.get('select').eq(0).select('14').should('include.text','lalitha g')
        cy.get('.test-header>:nth-child(4)').select('firstname Lokireddy').should('include.text','firstname Lokireddy')
        cy.get('.blue').click()
    })
    it.skip('WF2-curator Login',function(){
        cy.User1(CREDENTIALS.User1,CREDENTIALS.Pwd)
        cy.Workflow2()
    })
    it('WF2-Initial Reviewer query alert check',function(){
        cy.User2(CREDENTIALS.User2,CREDENTIALS.Pwd)
        cy.intercept('/workbench/home').as('home')
        cy.intercept('/workbench/taskMapping/taskInprogress').as('PTC')
        cy.intercept('//workbench/formMetadata/tasks/279729/entities/2/eavobjects?projectId=210&projectDataId=1517&subCollectionParentId=&stateTypeId=1').as('XRT')
        cy.contains('TestWF3').click()
        cy.wait(2000)
        cy.get(':nth-child(3) > .nav-link').click({force:true})
        Cypress.on('uncaught:exception', (err, runnable) => {return false;});        
        cy.get(':nth-child(3) > .nav-link > span').click({force:true})
        cy.contains('TestCypProject').click({force:true}).should('include.text','TestCypProject')
        cy.get('#react-tabs-20').click().should('have.text','Initial Review')
        cy.get('tbody > :nth-child(1) > :nth-child(5)').should('have.text','workflow2')
        cy.get('.react-bootstrap-table').scrollTo('right')
        cy.get('.orange2').should('be.visible').click()
        // cy.get(':nth-child(1) > :nth-child(11) > div > :nth-child(1) > .orange2').should('be.visible').click()
        cy.get('[title="Add"]').click()
        // Adding Data Elements
        cy.get('select').eq(0).select('Jan').should('include.text','Jan')
        cy.get('select').eq(1).select('1').should('include.text','1')
        cy.get('select').eq(2).select('1980').should('include.text','1980')
        
        cy.get('[name="3"]').type('Alive').should('have.value','Alive')

        cy.get('select').eq(3).select('Jan').should('include.text','Jan')
        cy.get('select').eq(4).select('1').should('include.text','1')
        cy.get('select').eq(5).select('2019').should('include.text','2019')
        cy.get('#react-select-wbSelectbox-1361 > .css-2b097c-container > .css-7aiczb-control > .css-1hwfws3')
        .type('Wh{enter}').should('include.text','White')
        cy.get('.react-datepicker__input-container > input').click()
        cy.get(':nth-child(1) > .react-datepicker__day--001').click()
        cy.get(':nth-child(14)>.inputField>[style="width: 100%;"]>label>[style="white-space: nowrap;"]>[title="Not Applicable"]>.fas')
        .click()
        cy.get('.blue').click()
        cy.wait(25000)
        // XRT data collection
        cy.get('#react-tabs-30').click().should('include.text','XRT1')
        cy.wait(25000)
        cy.get('[title="Add"]').click()
        cy.get('#react-select-wbSelectbox-1007>.css-2b097c-container>.css-7aiczb-control>.css-1hwfws3')
        .type('No{enter}').should('include.text','No')
        cy.get('[name="1008"]').type('Radtion Nill')
        cy.get('center > .blue').click()
        cy.wait(25000)
        cy.get('[title="Actions"]').invoke('mouseover')
        cy.get('[title="Review Data"]').click({force:true})
        cy.contains('Ok').click()
        cy.on('window:alert', (str) => {
            expect(str).to.equal('Do you like to lock all your task data and do review process ?')
        })
        cy.wait(4000)
        cy.get('#react-tabs-60').click({force:true}).should('include.text','patient_characteristics')
        cy.wait(25000)
        cy.get(':nth-child(4) > :nth-child(1) > .react-bootstrap-table').scrollTo('right')
        cy.get('[style="display: flex;"] > :nth-child(3)').scrollTo('bottom')
        cy.get('#CommentsId').type('Check XRT data').should('include.text','Check XRT data')
        cy.contains('Submit').click()
        cy.get('[title="Actions"]').invoke('mouseover')
        cy.get('[title="Active Review"]').click({force:true})
        cy.contains('Ok').click()
        cy.on('window:alert', (str) => {
            expect(str).to.equal('The task will be moved to Active Review. Please confirm.')
        })
    })
})